name: Sync to Hugging Face Hub

on:
  push:
    branches: [main] # 当main分支有更新时触发

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Kimin1999:$HF_TOKEN@huggingface.co/spaces/Kimin1999/smartTiTu-uic main
